### ISSUE TITLE
Ratings brake functionality on vinmonopolet.no

### ISSUE THREAD

**Issue by enedberg** [hyldmo/vm-vivino#1]
I´ll write this in Norwegian, as I guess you understand that. Please let me know if I am mistaken.

Jeg har installert din utvidelse "Vivino ratings for Vinmonopolet" i Chrome. Den er helt super!

Jeg har imidlertid oppdaget tre små "bugs", som alle er relaterte og fjerner funksjonalitet fra nettsiden

1. På produktsiden er det nesten umulig å benytte liste- og favoritt-knappene
2. I søkeresultatene (der det vises en liste over viner) er det nesten umulig å benytte liste- og favoritt-knappene
3. I handlevognen fungerer ikke linken til produktet (trykke på produktnavnet)

Dette skyldes at det i kilden for class="product__rating product-tools" settes style="left: 0.5rem; padding: 1rem;". Om dette endres til style="left: 0.5rem; padding: 1rem; width: fit-content;" så ser det ut til å fungere. Det finnes sikkert andre løsninger også.

Igjen: Takk for super utvidelse! Håper det er mulig for deg å fikse på dette slik at ikke funksjonalitet fjernes fra [vinmonopolet.no](http://vinmonopolet.no/)

**Comment by hyldmo** [comment]
Hei, ja er klar over det! Har fikset bugen, men chrome storen har blokkert meg fra å publisere nye versjoner av extensionen til jeg lager en privacy policy (som er noe tullete da jeg ikke lagrer noe data noe sted). La til det nå, så krysser fingrene for at den går igjennom

**Comment by hyldmo** [comment]
Ser ut som updaten har kommet igjennom nå, så lukker issuet
